apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kantox-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/kantox-dev.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: kantox-dev=gehal6/kantoxapp:latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:gehal6/KantoxK8s.git'
    path: ./kantox-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - dev-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
